permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

markdown: rdiscount

title : 缸中之脑
tagline: jvm应用外围调用隔离
author :
  name : leo
  github : zhenggc1
  twitter : zhenggc1

production_url : http://blog.kpush.info

JB :
  version : 0.3.0

  BASE_PATH : false

  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : false
    disqus :
      short_name : kpushblog
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-3090256-4'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  sharing :
    provider : false
    
  
